name: "multi vent pipeline/workflow"
on:
    push:
      branches:
        - master
        - test
    pull_request:
      branches:
        - master

jobs:
  on-push:
    #if: github.event_name == 'push'
    runs-on: ubuntu-latest 
    steps:
      - name: "running on master/test push"
        run: echo "running on master/test branch"

  on-pull-request:
   # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull request"
        run: echo "running on pull request"_  