name: "multi vent pipeline/workflow"
on:
    push:
      branches:
        - master
        - test
    pull_request:
      branches:
        - master
    workflow_dispatch:     
#there is something
jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest 
    steps:
      - name: "running on master/test push"
        run: echo "running on master/test branch"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull request"
        run: echo "running on pull request"_  

  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "running on workflow dispatch"
        run: echo "running on workflow dispatch"
